export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#dce9ff",
        "secondary-fixed": "#d8e2ff",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "surface": "#f8f9ff",
        "on-secondary-fixed": "#001a42",
        "tertiary-container": "#9699ff",
        "secondary": "#0058be",
        "on-secondary-fixed-variant": "#004395",
        "on-background": "#0b1c30",
        "outline": "#6c7a71",
        "on-surface": "#0b1c30",
        "on-error": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary-container": "#2170e4",
        "surface-container": "#e5eeff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "outline-variant": "#bbcabf",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-tint": "#006c49",
        "on-tertiary-fixed": "#07006c",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#1d17b2",
        "primary": "#006c49",
        "tertiary-fixed": "#e1e0ff",
        "on-primary-fixed-variant": "#005236",
        "background": "#f8f9ff",
        "tertiary": "#494bd6",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#002113",
        "on-error-container": "#93000a",
        "primary-container": "#10b981",
        "on-secondary": "#ffffff",
        "on-primary-container": "#00422b",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#3c4a42",
        "primary-fixed": "#6ffbbe",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#4edea3",
        "inverse-primary": "#4edea3",
        "error": "#ba1a1a",
        "on-secondary-container": "#fefcff",
        profit: '#10b981',
        loss:   '#ef4444',
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "stack_lg": "32px",
        "gutter": "24px",
        "card_padding": "24px",
        "stack_md": "16px",
        "margin_page": "32px",
        "sidebar_width": "280px",
        "stack_sm": "8px"
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'Inter', 'system-ui', 'sans-serif'],
        "label-md": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-sm": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg": ["40px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "700"}]
      },
      boxShadow: {
        'card': '0 2px 15px -3px rgba(0,0,0,0.07), 0 10px 20px -2px rgba(0,0,0,0.04)',
        'card-dark': '0 2px 15px -3px rgba(0,0,0,0.3)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s infinite',
      }
    }
  },
  plugins: [],
}
